title: Hipster Bill Raymond
description: Home to my upcoming website!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
url: "https://HipsterBillRaymond.github.io"
baseurl: "/my-rockin-github-pages-site"